inven/inven/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomePage.as_view(), name='home'),
    path('products/', include('products.urls', namespace='products')),
    path('locations/', include('locations.urls', namespace='locations')),
    path('mov/', include('productmovement.urls', namespace='productmovement')),
    
]

inven/locations/urls.py
from django.urls import path
from .views import (
                    LocationCreateView,
                    LocationDetailView,
                    LocationDeleteView,
                    LocationListView,
                    LocationUpdateView,
)
app_name= 'locations'
urlpatterns = [
    path ('', LocationListView.as_view(), name = 'location-list'),
    path ('<int:id>/', LocationDetailView.as_view(), name = 'location-detail'),
    path ('create/', LocationCreateView.as_view(), name = 'location-create'),
    path ('<int:id>/update/', LocationUpdateView.as_view(), name = 'location-update'),
    path ('<int:id>/delete/', LocationDeleteView.as_view(), name = 'location-delete'),
]

inven/productmovement/urls.py
from django.urls import path
from .views import (
                    ProductMovementCreateView,
                    ProductMovementDetailView,
                    ProductMovementListView,
                    ProductMovementUpdateView,
                    ProductMovementDeleteView
)
app_name= 'productmovement'
urlpatterns = [
    path ('', ProductMovementListView.as_view(), name = 'productmov-list'),
    path ('createmov/', ProductMovementCreateView.as_view(), name = 'productmov-create'),
    path ('<int:id>/', ProductMovementDetailView.as_view(), name = 'productmov-detail'),
    path ('<int:id>/update/', ProductMovementUpdateView.as_view(), name = 'productmov-update'),
    path ('<int:id>/delete/', ProductMovementDeleteView.as_view(), name = 'productmov-delete'),

]

inven/products/urls.py
from django.urls import path
from .views import (
                    ProductCreateView,
                    ProductDeleteView,
                    ProductDetailView,
                    ProductListView,
                    ProductUpdateView
)
app_name= 'products'
urlpatterns = [
    path ('', ProductListView.as_view(), name = 'product-list'),
    path ('<int:id>/', ProductDetailView.as_view(), name = 'product-detail'),
    path ('create/', ProductCreateView.as_view(), name = 'product-create'),
    path ('<int:id>/update/', ProductUpdateView.as_view(), name = 'product-update'),
    path ('<int:id>/delete/', ProductDeleteView.as_view(), name = 'product-delete'),

]

inven/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
   
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
  
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ home }}">Home</a>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'products:product-list' %}">Products <span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'locations:location-list' %}">Locations</a></li>
            <li><a href="{% url 'productmovement:productmov-create' %}">Create Movement</a></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'products:product-create' %}">Product</a></li>
                <li><a href="{% url 'locations:location-create' %}">Location</a></li>
                <li><a href="{% url 'productmovement:productmov-create' %}">Product Movement</a></li>
              

                <li role="separator" class="divider"></li>
                <li><a href="{% url 'products:product-list' %}">Update</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
          
              
            </div>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>



    <div class="jumbotron mycontent">
        {% block content %}

        {% endblock %}

    </div>
    
</body>

</html>

inven/templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Inventory list!</h1>
   

{% endblock %}